### ISSUE TITLE
JSchException:Session.connect:java.io.IOException: End of IO Stream Read

### ISSUE THREAD

**Issue by harlan-zhao** [harlan-zhao/smonitor#1]
JSch版本：0.1.54
主机OpenSSH版本  7.3p1
com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read
	at com.jcraft.jsch.Session.connect(Session.java:558)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.harlan.smonitor.monitor.common.SshConnecter.<init>(SshConnecter.java:45)
	at com.harlan.smonitor.monitor.core.connection.SshPool.getSsh(SshPool.java:26)

**Comment by harlan-zhao** [comment]
在/etc/ssh/sshd_config中加入
`KexAlgorithms diffie-hellman-group1-sha1`
参考：
[http://stackoverflow.com/questions/37280442/jsch-0-1-53-session-connect-throws-end-of-io-stream-read](url)
